<#
   ENGLISH (United Kingdom)

   Mike
   support@myrandomthoughts.co.uk
#>

#################################################################################################
#                                                                                               #
#  STRINGS FOR THE MAIN QA CHECKING SCRIPT ENGINE                                               #
#                                                                                               #
#################################################################################################

[engine]
    # General
Header         = 'Starting QA Procedure'
Admin-Warn_1   = 'You are not running this script as an administrator'
Admin-Warn_2   = 'Restart PowerShell with the "Run as Administrator" option'
Scan-Head_1    = 'There are {0} checks to perform, with a maximum of {1} running concurrently'
Scan-Head_2    = 'Each has a timeout limit of {0} seconds.  Progress bar legend:'
Servers        = 'servers'
Verbose-Info   = 'Verbose information:'

    # HELP Screen
Help_01        = 'Usage Information'
Help_02        = 'Quick Usage:'
Help_03        = 'Examples:'
Help_04        = 'Local Server Only:'
Help_05        = 'Use a period (.) to indicate the localhost, or use the servername:'
Help_06        = 'Multiple Servers:'
Help_07        = 'Using commas (,) to separate, add each server to the command line:'
Help_08        = 'Using a text file, with each server on a separate line:'
Help_09        = 'Please Note:'
Help_10        = 'The script connects using the same credentials as the powershell window.'
Help_11        = 'To connect using different credentials, Shift + Right-click the PowerShell'
Help_12        = 'icon in the Start Menu and select "Run as different user".  Enter the user'
Help_13        = 'details required and then re-run the script.'
Help_14        = ''
Help_15        = ''
Help_16        = ''
Help_17        = ''
Help_18        = ''
Help_19        = ''
Help_20        = ''

    # SCAN Error messages
AD-Message     = 'ACCESS DENIED'
AD-Write-Host  = 'ACCESS DENIED - Skipping all scripts for server'
ND-Name        = 'NO DATA'
ND-Message     = 'Error while running, job returned no data'
FD-Message     = 'Job failed to run or the remote server was disconnected'
FD-Write-Host  = 'JOB FAILED/DISCONNECTED - Skipping all scripts for server'
TO-Name        = 'TIMEOUT'
TO-Message     = 'Job failed to finish within the timeout period, job cancelled'
RPC-Message    = 'RPC FAILURE while communicating with the server, check the firewall ports are opened correctly'
RPC-Write-Host = 'RPC FAILURE - Skipping all scripts for server'
CF-Message     = 'CONNECTION FAILURE while contacting the server, check that the server switched on and working'
CF-Write-Host  = 'CONNECTION FAILURE - Skipping all scripts for server'

    # RESULTS Shows on PowerShell screen
ServerCount    = 'Scanning {0} servers'    #
TotalCount_1   = 'Total Server Counts'     # Total count of the number of servers scanned
Checked        = 'Checked'                 # 
Skipped        = 'Skipped'                 # 
TotalCount_2   = 'Total Script Results'    # Total count of the script results (Passed, Failed, ...)
Pass           = 'Pass'                    # 
Passed         = 'Passed'                  # 
Warning        = 'Warning'                 # 
Fail           = 'Fail'                    # 
Failed         = 'Failed'                  # 
Manual         = 'Manual'                  # 
Not-Applicable = 'N/A'                     # 
Error          = 'Error'                   # 
TimeTaken      = 'Approx Time Taken :'     # 
ReportsLocated = 'Reports Located In:'     # 

    # HTML Report
QA-Results     = 'QA Results'              # Page header
Script-Version = 'Script Version:'         # Script Version: (version)
Generated-By   = 'Generated by'            # Generated By (username) on (date)
On             = 'on'                      #
Applies-To     = 'Applies To'              # Part of the HTML hover help.

    # HTML Columns
HTML_Name      = 'Name'                    # The short name of the check
HTML_Check     = 'Check'                   # The check code (ACC-01)
HTML_Result    = 'Result'                  # The check result (Pass, Fail, ...)
HTML_Message   = 'Message'                 # The message retuned to the user
HTML_Data      = 'Data'                    # The informational data returned

    # HTML Sections
Accounts      = 'Accounts'                 # User and group accounts
Compliance    = 'Compliance'               # Tooling agent checks (AV, SCOM, SCCM, etc)
Drives        = 'Drives'                   # Local disk drive information
HyperV-Host   = 'HyperV Host'              # Microsoft Hyper-V host systems (not guests)
Network       = 'Network'                  # Local area networking information
Regional      = 'Regional'                 # Localised keyboard/language settings
Security      = 'Security'                 # Security and firewall checks
System        = 'System'                   # Local computer system checks
VMs-HyperV    = 'VMs: HyperV'              # Computers that are Hyper-V guests (not hosts)
VMs-VMware    = 'VMs: VMware'              # Computers that are VMware ESX guests (not hosts)

#################################################################################################
#                                                                                               #
#  COMMON STRINGS APPLIED TO ALL CHECKS                                                         #
#                                                                                               #
#################################################################################################

[common]
Pass           = 'Pass'
Warning        = 'Warning'
Fail           = 'Fail'
Manual         = 'Manual'
Not-Applicable = 'N/A'
Error          = 'Error'
Script-Error   = 'SCRIPT ERROR'

#################################################################################################
#                                                                                               #
#  QA CHECK STRINGS                                                                             #
#                                                                                               #
#################################################################################################

#################################################################################################
# ACCOUNTS

[acc01]
Name = 'Local Users'
A    = 'One or more local accounts exist'
B    = 'No additional local accounts'
C    = 'This is a workgroup server, is this correct.?'

[acc02]
Name = 'Local Account Names'

[acc03]
Name = 'Local Admins'

[acc04]
Name = 'Local Groups'

[acc05]
Name = 'Service Logon Accounts'

[acc06]
Name = 'Guest Account'

#################################################################################################
# COMPLIANCE

[com01]
Name = 'McAfee AV Installed'

[com02]
Name = 'Monitoring Installed'

[com03]
Name = 'SCCM Installed'

[com04]
Name = 'NetBackup Agent Installed'

[com05]
Name = 'Patching Compliant'

[com06]
Name = 'WSUS Server Setting'

[com07]
Name = 'Sentinel Agent Installed'

